version: "3"

services:
  app:
    build:
      context: .
    container_name: strapi_6d_sms
    restart: unless-stopped
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    env_file:
      - stack.env