version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi_6d_sms
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/srv/app
