version: "3"

services:
  app:
    build:
      context: ./app
    container_name: strapi_6d_sms
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
