version: "3"

services:
  app:
    env_file:
      - ./app/.env
    build:
      context: ./app
    container_name: strapi_6d_sms
    restart: unless-stopped

    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
