providers = ["node"]

[phases.install]
cmds = ['npm install'] 

[phases.build]
cmds = ['npm run build'] 

[variables]
NODE_ENV = 'production' 
NIXPACK_NODE_VERSION = '16' 
NPM_CONFIG_PRODUCTION = true

[start]
cmd = 'npm run start' 
