    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sms-gateway-prod
      namespace: six-degrees-apps
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: sms-gateway-prod
      template:
        metadata:
          labels:
            app: sms-gateway-prod
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
          - name: sms-gateway-prod
            image: ghcr.io/6degrees/js_strapi_6d_sms_gateway:latest
            ports:
              - containerPort: 1337
            envFrom:
              - secretRef:
                  name: sms-gateway-prod-secrets
              - configMapRef:
                  name: sms-gateway-prod-configmap
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            readinessProbe:
              httpGet:
                path: /_health
                port: 1337
              initialDelaySeconds: 30
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /_health
                port: 1337
              initialDelaySeconds: 60
              periodSeconds: 20
