apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sms-gateway-prod-secrets
  namespace: six-degrees-apps
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sms-gateway-prod-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: ADMIN_JWT_SECRET
    - secretKey: API_TOKEN_SALT
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: API_TOKEN_SALT
    - secretKey: APP_KEYS
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: APP_KEYS
    - secretKey: DATABASE_HOST
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: DATABASE_HOST
    - secretKey: DATABASE_NAME
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: DATABASE_NAME
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: DATABASE_USERNAME
    - secretKey: FIRST_VALUE_CLIENT_ID
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: FIRST_VALUE_CLIENT_ID
    - secretKey: FIRST_VALUE_CLIENT_PASSWORD
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: FIRST_VALUE_CLIENT_PASSWORD
    - secretKey: FIRST_VALUE_SENDER_NAME
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: FIRST_VALUE_SENDER_NAME
    - secretKey: FIRST_VALUE_TOKEN
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: FIRST_VALUE_TOKEN
    - secretKey: JWT_SECRET
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: JWT_SECRET
    - secretKey: MSEGAT_API_KEY
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: MSEGAT_API_KEY
    - secretKey: MSEGAT_USERNAME
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: MSEGAT_USERNAME
    - secretKey: TAQANYAT_BASE_URL
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: TAQANYAT_BASE_URL
    - secretKey: TAQANYAT_SENDER_NAME
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: TAQANYAT_SENDER_NAME
    - secretKey: TAQANYAT_TOKEN
      remoteRef:
        key: six-degrees/sms-gateway/secrets
        property: TAQANYAT_TOKEN
