[phases.install]
cmds = ['pnpm install'] # Changed to pnpm as per your preference

[phases.build]
cmds = ['pnpm build'] # Changed to pnpm

[variables]
NODE_ENV = 'production' # Setting the environment to production
NIXPACK_NODE_VERSION = '20' # Specifying Node.js version

[start]
cmd = 'pnpm start' # Changed to pnpm
